### ISSUE TITLE
DB maintenance fail

### ISSUE THREAD

**Issue by SorinGFS** [aaemnnosttv/wp-sqlite-db#19]
When things in WP (posts, pages, etc) are trashed, then deleted permanently they stil continue to exist in database with a different status, and they are not appearing anymore in WP as garbage. I don't know if this is the normal behaviour for this drop in, but I think this is a problem since database will continue to grow. The original Sqlite Integration had an internal tool working just fine and maintaining the database clean.

**Comment by aaemnnosttv** [comment]
Oh that's odd; I was not aware of that behavior 🤔  I'll take a look 👍

**Comment by SorinGFS** [comment]
> 
> 
> Oh that's odd; I was not aware of that behavior thinking I'll take a look +1

Any resolution so far?

I copied the old good `Sqlite-Integration` plugin into plugins folder and activated it. Except some `undefined function` errors **it works!** I was able to `vacuum` the database, and make a backup.

![321321](https://user-images.githubusercontent.com/25417015/113392870-77dcb180-939e-11eb-8b70-970d37814645.png)

Can't you at least integrate the vacuum and backup functionalities?

**Comment by aaemnnosttv** [comment]
After taking a closer look here, both database optimization and backup do not require any additional support from the core DB driver which is where wp-sqlite-db differentiates itself with the SQLite Integration plugin.

This project is designed to be a minimal low-level component for making the database connection and as such will likely never have any interface like the previous plugin did. I understand how this is important functionality, but it's still possible as-is, the interface just makes it accessible for the average admin in WP. For that, another plugin could be written (or these parts pulled into a separate plugin from the original).

So to your original question, the database can be optimized using wp-cli like so:
```
wp eval '$GLOBALS["wpdb"]->query("OPTIMIZE");'
```
This is [the same thing that the plugin does](https://github.com/aaemnnosttv/wp-sqlite-integration/blob/4dbb7d91ded8e268b6dfcc56243433c37782d21d/utilities/utility.php#L303), just in a CLI command (wp-cli also has a `db query` command but this won't work because it tries to connect to a mysql db).

Backing up the database is as simple as making a copy of the database file just like any other, which by default is in `wp-content/database/.ht.sqlite`.

Again, neither of these things require any special support in the core driver here so there's nothing more to do 😄 

I may however create a new plugin that addresses some of these concerns since a database file that grows forever isn't very scalable either.

Thanks again for raising this.

**Comment by SorinGFS** [comment]
OK thanks. I think it wouldn't  hurt to advertise this on the main readme page:

> So to your original question, the database can be optimized using wp-cli like so:
> 
> ```
> wp eval '$GLOBALS["wpdb"]->query("OPTIMIZE");'
> ```

I look forward to the new plugin.
