### ISSUE TITLE
don't work on Mac OS Mojave.

### ISSUE THREAD

**Issue by rockyzhng** [aaemnnosttv/wp-sqlite-db#2]
OS: macOS Mojave comes with Apache,php,sqlite pre-installed.
Apache/2.4.41 (Unix) Nov  9 2019 07:53:54
PHP 7.3.9 (cli) (built: Nov  9 2019 08:08:13) ( NTS )
SQLite version 3.28.0 2019-04-15

**Comment by aaemnnosttv** [comment]
Can you elaborate on how you're trying to use it?

You don't need to have sqlite installed separately. The sqlite extension has been [bundled with PHP since v5.0](https://www.php.net/manual/en/sqlite.installation.php).

**Comment by rockyzhng** [comment]
Thanks for your reply,
I didn't install any SQLite separately. i know sqlite already pre-installed in new Mac OS . only do these things as following:
1. download latest Wordpress and copy all files to /Library/WebServer/Documents/
2. Copy src/db.php into /Library/WebServer/Documents/wp-content/
3. Change wp-config-sample.php name to  wp-config.php
4. Start Apache web server: sudo apachectl start
5. Safari go to 127.0.0.1/index.php to install Wordpress.
6. this step goes wrong: Unable to create the required directory! Please check your server settings.
Please tell me what I did wrong, Thanks.

**Comment by aaemnnosttv** [comment]
I've never seen that error before, and that text does not exist in WordPress so it may be coming from Apache? I'm not sure.

Do you see the WordPress install screen at all?
![image](https://user-images.githubusercontent.com/1621608/72324216-135b0700-36b3-11ea-86e0-2c761ff13105.png)

This part does not require a database at all so you should be able to see that.

If not, try loading a simple php file in the browser (not WordPress) to see if the web server is working first.

E.g. `index.php`
```php
<?php phpinfo();
```

The error sounds related to file permissions though which could be because your installation location is all owned by `root` which Apache is probably not running as. Try moving your document root to something under your user's home directory.

**Comment by rockyzhng** [comment]
it's done.

Switch Document Root to the user home directory, and chmod -R 777.

Thank you very much!
