### ISSUE TITLE
WordPress 6.1 adds new method call wpdb->db_server_info() in dbDelta 

### ISSUE THREAD

**Issue by andreasnrb** [aaemnnosttv/wp-sqlite-db#44]
The SQLite drop in is missing the implementation of function db_server_info() {}.

```
	    /**
	     * Retrieves full database server information.
	     *
	     * @since 5.5.0
	     *
	     * @return string|false Server info on success, false on failure.
	     */
	    public function db_server_info() {
		    return 'somestring';
	    }
```

**Comment by aaemnnosttv** [comment]
Hi there! Our class [extends `wpdb`](https://github.com/aaemnnosttv/wp-sqlite-db/blob/3aa1a8822af2544c88733827609353c1ad68aec1/src/db.php#L2494) so it isn't missing the implementation, but it seems that the core implementation depends on one of the mysql functions which would raise an error. We need to override this with a value that returns a string in a similar format to `mysqli_get_server_info`.

Feel free to open a PR, otherwise I'll try to address this soon.

**Comment by andreasnrb** [comment]
The function call is just used to detect if MariaDb is used due to it not supporting table columns with ( ) as MySQL does. So any string will do I think. Returning SQLite3 is prudent I think. Did not seem that it should return MariaDb based on the SQLite docs.

**Comment by joy-software** [comment]
Hi, I was facing the same issue. I fixed it by adding this small portion of code at the end of the class wpsqlitedb like @andreasnrb  suggested.

`/**
         * Retrieves full database server information.
         *
         * @since 5.5.0
         *
         * @return string Server info on success, false on failure.
         */
        public function db_server_info() {
            return 'SQLite3';
        }`
